=== jomifm/CoreSnmp/coresnmp/cfg/coresnmp-configuration-1.0.dtd
<!-- coresnmp file-based configuration document.

<!DOCTYPE coresnmp-configuration SYSTEM "coresnmp-configuration-1.0.dtd">

An instance of this document contains property settings and references
to mapping files for a number of SessionFactory instances to be listed
in SNMP.

-->

<!ELEMENT coresnmp-configuration (session-factory,security?)>

<!ELEMENT property (#PCDATA)>
	<!ATTLIST property name CDATA #REQUIRED>

<!ELEMENT mapping EMPTY> <!-- reference to a mapping file -->
	<!ATTLIST mapping resource CDATA #IMPLIED>
	<!ATTLIST mapping mib CDATA #IMPLIED>

<!ELEMENT object (#PCDATA)>
	<!ATTLIST object name CDATA #REQUIRED>
	<!ATTLIST object oid CDATA #REQUIRED>
	<!ATTLIST object parent CDATA #IMPLIED>
	<!ATTLIST object type (integer|string|ipaddress) #IMPLIED>
	<!ATTLIST object access (read-only|read-write|write-only) #IMPLIED>
	<!ATTLIST object description CDATA #IMPLIED>

<!ELEMENT trap (#PCDATA)>

<!ELEMENT notification (#PCDATA)>

=== jomifm/CoreSnmp/coresnmp/cfg/coresnmp.cfg.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE coresnmp-configuration SYSTEM 
	"coresnmp-configuration-1.0.dtd">

<coresnmp-configuration>
   
   <property name="logger.dialect">stdout</property>
   <property name="logger.level">debug</property>
   <property name="logger.file">log/coresnmp.log</property>
   
   <property name="config.version">1</property>
   <property name="config.rocommunity">public</property>
   <property name="config.rwcommunity">private</property>
   <property name="config.trapcommunity">public</property>

   <property name="connection.request.nms.port">161</property>
   <property name="connection.request.agent.port">1610</property>

   <property name="connection.trap.nms.address">192.168.255.255</property>
   <property name="connection.trap.nms.port">1620</property>
   <property name="connection.trap.agent.port">1620</property>

   <mapping resource="cfg/coresnmp-requests.mib.xml"/>
   <mapping resource="cfg/coresnmp-traps.mib.xml"/>

</coresnmp-configuration>
